spring.application.name=DiloBackend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration={JWT_EXPIRATION}


supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=imagenes

spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=50MB


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587 
spring.mail.username=${USER_BREVO}
spring.mail.password=${API_KEY_BREVO}
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

brevo.sender.email=${EMAIL_BREVO}
brevo.sender.name=Sistema Dilo